server:
  port: 7709
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
      discovery: #????????
        locator: #??????
          enabled: false #????????????
          lower-case-service-id: true #???????????
      routes: #?????????????????????????????????
        - id: header-api #??????????????
          uri: lb://service-header #?????????????? lb??loadbalance
          predicates:
            - Path=/api/header-api/** #??????????????=???name???   args???
          filters: #???????
             #????????????????=???name???   args???
            - StripPrefix=2 #??????????????????2??/api?2?????/api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7706/eureka/

authen:
  jwt:
    signature: JuBi
  unauth:
    excludePaths:
      - /**/header/**
      - /laster/login
